<?php
namespace jocoon\parquet\format;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Supported compression algorithms.
 * 
 * Codecs added in 2.4 can be read by readers based on 2.4 and later.
 * Codec support may vary between readers based on the format version and
 * libraries available at runtime. Gzip, Snappy, and LZ4 codecs are
 * widely available, while Zstd and Brotli require additional libraries.
 */
final class CompressionCodec
{
    const UNCOMPRESSED = 0;

    const SNAPPY = 1;

    const GZIP = 2;

    const LZO = 3;

    const BROTLI = 4;

    const LZ4 = 5;

    const ZSTD = 6;

    static public $__names = array(
        0 => 'UNCOMPRESSED',
        1 => 'SNAPPY',
        2 => 'GZIP',
        3 => 'LZO',
        4 => 'BROTLI',
        5 => 'LZ4',
        6 => 'ZSTD',
    );
}

