<?php
namespace codename\parquet\format;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Supported compression algorithms.
 * 
 * Codecs added in format version X.Y can be read by readers based on X.Y and later.
 * Codec support may vary between readers based on the format version and
 * libraries available at runtime.
 * 
 * See Compression.md for a detailed specification of these algorithms.
 */
final class CompressionCodec
{
    const UNCOMPRESSED = 0;

    const SNAPPY = 1;

    const GZIP = 2;

    const LZO = 3;

    const BROTLI = 4;

    const LZ4 = 5;

    const ZSTD = 6;

    const LZ4_RAW = 7;

    static public $__names = array(
        0 => 'UNCOMPRESSED',
        1 => 'SNAPPY',
        2 => 'GZIP',
        3 => 'LZO',
        4 => 'BROTLI',
        5 => 'LZ4',
        6 => 'ZSTD',
        7 => 'LZ4_RAW',
    );
}

