<?php
namespace jocoon\parquet\format;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class EncryptionAlgorithm
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'AES_GCM_V1',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\jocoon\parquet\format\AesGcmV1',
        ),
        2 => array(
            'var' => 'AES_GCM_CTR_V1',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\jocoon\parquet\format\AesGcmCtrV1',
        ),
    );

    /**
     * @var \jocoon\parquet\format\AesGcmV1
     */
    public $AES_GCM_V1 = null;
    /**
     * @var \jocoon\parquet\format\AesGcmCtrV1
     */
    public $AES_GCM_CTR_V1 = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['AES_GCM_V1'])) {
                $this->AES_GCM_V1 = $vals['AES_GCM_V1'];
            }
            if (isset($vals['AES_GCM_CTR_V1'])) {
                $this->AES_GCM_CTR_V1 = $vals['AES_GCM_CTR_V1'];
            }
        }
    }

    public function getName()
    {
        return 'EncryptionAlgorithm';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->AES_GCM_V1 = new \jocoon\parquet\format\AesGcmV1();
                        $xfer += $this->AES_GCM_V1->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->AES_GCM_CTR_V1 = new \jocoon\parquet\format\AesGcmCtrV1();
                        $xfer += $this->AES_GCM_CTR_V1->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('EncryptionAlgorithm');
        if ($this->AES_GCM_V1 !== null) {
            if (!is_object($this->AES_GCM_V1)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('AES_GCM_V1', TType::STRUCT, 1);
            $xfer += $this->AES_GCM_V1->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->AES_GCM_CTR_V1 !== null) {
            if (!is_object($this->AES_GCM_CTR_V1)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('AES_GCM_CTR_V1', TType::STRUCT, 2);
            $xfer += $this->AES_GCM_CTR_V1->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
