<?php
namespace jocoon\parquet\format;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Representation of Schemas
 */
final class FieldRepetitionType
{
    /**
     * This field is required (can not be null) and each record has exactly 1 value.
     */
    const REQUIRED = 0;

    /**
     * The field is optional (can be null) and each record has 0 or 1 values.
     */
    const OPTIONAL = 1;

    /**
     * The field is repeated and can contain 0 or more values
     */
    const REPEATED = 2;

    static public $__names = array(
        0 => 'REQUIRED',
        1 => 'OPTIONAL',
        2 => 'REPEATED',
    );
}

