<?php
namespace jocoon\parquet\format;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class OffsetIndex
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'page_locations',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\jocoon\parquet\format\PageLocation',
                ),
        ),
    );

    /**
     * PageLocations, ordered by increasing PageLocation.offset. It is required
     * that page_locations[i].first_row_index < page_locations[i+1].first_row_index.
     * 
     * @var \jocoon\parquet\format\PageLocation[]
     */
    public $page_locations = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['page_locations'])) {
                $this->page_locations = $vals['page_locations'];
            }
        }
    }

    public function getName()
    {
        return 'OffsetIndex';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::LST) {
                        $this->page_locations = array();
                        $_size49 = 0;
                        $_etype52 = 0;
                        $xfer += $input->readListBegin($_etype52, $_size49);
                        for ($_i53 = 0; $_i53 < $_size49; ++$_i53) {
                            $elem54 = null;
                            $elem54 = new \jocoon\parquet\format\PageLocation();
                            $xfer += $elem54->read($input);
                            $this->page_locations []= $elem54;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('OffsetIndex');
        if ($this->page_locations !== null) {
            if (!is_array($this->page_locations)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('page_locations', TType::LST, 1);
            $output->writeListBegin(TType::STRUCT, count($this->page_locations));
            foreach ($this->page_locations as $iter55) {
                $xfer += $iter55->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
