<?php
namespace jocoon\parquet\format;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class PageType
{
    const DATA_PAGE = 0;

    const INDEX_PAGE = 1;

    const DICTIONARY_PAGE = 2;

    const DATA_PAGE_V2 = 3;

    static public $__names = array(
        0 => 'DATA_PAGE',
        1 => 'INDEX_PAGE',
        2 => 'DICTIONARY_PAGE',
        3 => 'DATA_PAGE_V2',
    );
}

