<?php
namespace jocoon\parquet\format;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Types supported by Parquet.  These types are intended to be used in combination
 * with the encodings to control the on disk storage format.
 * For example INT16 is not included as a type since a good encoding of INT32
 * would handle this.
 */
final class Type
{
    const BOOLEAN = 0;

    const INT32 = 1;

    const INT64 = 2;

    const INT96 = 3;

    const FLOAT = 4;

    const DOUBLE = 5;

    const BYTE_ARRAY = 6;

    const FIXED_LEN_BYTE_ARRAY = 7;

    static public $__names = array(
        0 => 'BOOLEAN',
        1 => 'INT32',
        2 => 'INT64',
        3 => 'INT96',
        4 => 'FLOAT',
        5 => 'DOUBLE',
        6 => 'BYTE_ARRAY',
        7 => 'FIXED_LEN_BYTE_ARRAY',
    );
}
