language: php

matrix:
    fast_finish: true
    # allow_failures:
    #   - php: 7.1
    #   - php: 7.2
    include:
      - php: 7.3
      - php: 7.4
      - php: 8.0
        # ignore platform reqs
        # as some dependencies do not support PHP8 officially at the time of writing
        env: COMPOSER_IGNORE_PLATFORM_REQS=1

before_install:
    # install php-ext-snappy
    - git clone --recursive --depth=1 https://github.com/kjdev/php-ext-snappy.git
    - cd php-ext-snappy
    - export CXXFLAGS=-std=c++11
    - phpize
    - ./configure
    - make
    - make install
    - echo "extension = snappy.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    # disable XDebug for now
    - phpenv config-rm xdebug.ini

install:
    - cd $TRAVIS_BUILD_DIR
    - composer self-update
    - |
      if [ $COMPOSER_IGNORE_PLATFORM_REQS == "1" ]; then
        composer update --ignore-platform-reqs
      else
        composer update
      fi

script:
    - cd $TRAVIS_BUILD_DIR
    - vendor/bin/phpunit tests
